version: '3.8'
services:
  db:
    image: postgres:15
    container_name: gestao-vagas-db
    ports:
      - ${PC_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data-gestao-vagas
  prometheus:
    image: prom/prometheus:latest
    container_name: gestao-vagas-prometheus
    ports:
      - 9090:9090
    networks:
      - gv-network
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

networks:
  gv-network:
    driver: bridge

volumes:
  postgres_data:
  prometheus_data: