spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_vagas
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

jwt.secret=JAVAGAS_@337#
jwt.secret.candidate=JAVAGAS_@337#CANDIDATE